# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TinyCore
email: 
description: The Jekyll version of the Phantom theme by HTML5 UP.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bau.wat.ruhr" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logo.png
font-awesome-icon-logo:

collections:
  posts:
    title: Posts
    output: true
  steps:
    title: Steps
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: steps
  values:
    title: 
    date: 2016-09-01 00:00:00 -0700

# Social settings
github_username: 16stelter
twitter_username: 
facebook_URL: 
instagram_username: 
dribbble_username: 
500px_username: 
phone: 

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
